package cli

import (
	"context"
	"fmt"

	fang "charm.land/fang/v2"
	"github.com/spf13/cobra"

	"github.com/OWNER/REPLACE_TOOL/internal/version"
)

// execute runs the prepared root command and returns its error, already rendered
// to stderr. It is the single seam where charmbracelet/fang's styling is applied.
//
// Fang is deliberately isolated here and is NOT load-bearing (ADR-0004): reassign
// this var to plainExecute to drop fang entirely — stock cobra, one fewer
// dependency — without touching any command definition or the exit-code mapping
// in runCmd.
var execute = fangExecute

// fangExecute runs the command through fang for styled help, usage, and errors.
// Man pages are generated by cobra/doc (see manpages.go), not fang's single
// whole-tool `man` command, so it is disabled here (ADR-0004). Fang auto-detects
// color from the terminal and honors NO_COLOR.
func fangExecute(ctx context.Context, root *cobra.Command) error {
	b := version.Get()
	return fang.Execute(ctx, root,
		fang.WithoutManpage(),
		fang.WithVersion(b.Version),
		fang.WithCommit(b.Commit),
	)
}

// plainExecute is the dependency-free alternative to fangExecute: stock cobra
// execution plus our own minimal error line. Both honor the root's configured
// streams, so runCmd's exit-code mapping is identical either way.
func plainExecute(ctx context.Context, root *cobra.Command) error {
	err := root.ExecuteContext(ctx)
	if err != nil {
		fmt.Fprintln(root.ErrOrStderr(), "error:", err)
	}
	return err
}
